#+options: todo:t
#+title: Architecture Decision Records
#+date: <2024-02-15 Do>
#+author: Christian Egli
#+email: christian.egli@sbs.ch
#+language: en

#+TODO: DRAFT PROPOSED | ACCEPTED REJECTED DEPRECATED SUPERSEDED

* PROPOSED Deployment Scenarios
- Deciders :: CE, MK, US, MM
- Date :: [2024-02-29 Do]

We have a legacy system, a Python2/Django application, that powers the
production of books. The Django framework has enabled us to create the
application quickly but limits us now as we need to have more advanced
access to the database. That is why all of the newer functionality is
written using Clojure, Clojurescript and React.

The two web applications run side by side and provide more or less
separate functionality.

The goal is however to eventually replace all of the Python2/Django
application with Clojure. As this is a lot of work and doesn't bring
any tangible user value, we'd like to do this gradually while
implementing new features.

** Context and Problem Statement

When implementing the ignore feature for unknown words we had to move
the file upload to the new application. So now there are two places
where a user can upload a file. When using the old upload the unknown
words will not work correctly. This is confusing to the user.

However, the upload not just in the upload form, it is also contained
in the inline editor where the user an edit the DTBook XML and save,
aka upload, a new version.

** Decision Drivers

- We want to replace the Python2/Django application eventually,
  probably not now though
- There should be only one way to upload a file for the user
- We would like the migration to be a gradual process, minimizing the
  risk at each step
- There should be as little change in the UI as possible to avoid
  confusing the user

** Considered Options

- D-Day :: Only deploy once *everything* is migrated
- Strangler :: Replace functionality piece by piece
- Parallel :: Deploy new functionality without removing the old one

** Decision Outcome

Chosen option: Strangler, i.e. have both UIs in parallel and hide the
upload functionality (version and image upload and the markup editor)
in the old UI

*** Positive Consequences

- There is only one way to upload
- more functionality has been migrated from the legacy to the new
  application

*** Negative Consequences

- Iteration2 will take longer as we will also have to implement the
  markup editor in the new UI
- The old UI will look increasingly bare

** Pros and Cons of the Options

*** D-Day

Nothing is deployed before everything is migrated.

- Good :: The UI is consistent
- Bad :: Takes a long time to deliver
- Bad :: High risk (all or nothing)
- Bad :: Potential user experience disruption
- Bad :: Significant upfront investment
- Bad :: Implement things that might not be needed

*** Strangler

As we migrate functionality from the old system to the new we will
simply hide it in the old system. This is basically what we have been
doing for the last year.

The implication of this is that (since we migrated the file upload
functionality) we will also have to migrate the markup editor since it
essentially also does file upload. However this might be a lot of work
that we did not plan to do at this time.

As it turns out the markup editor is extremely simple: it is basically
just a textarea inside a form. Maybe it would be that much work to
migrate it.

- Good :: The changes are incremental for the user
- Bad :: More work than we had anticipated
- Bad :: The old UI will look pretty bare and have very little
  functionality

*** Parallel

We leave both UIs as they are and let the user choose which one she
will use.

- Good :: No need to change the legacy app
- Bad :: Confusing for the user as there are two ways to upload a file
  which behave slightly differently

** Links

- an article from Microsoft Learn about the [[https://learn.microsoft.com/en-us/azure/architecture/patterns/strangler-fig][Strangler Fig pattern]]
- [[https://medium.com/@josesousa8/the-strangler-pattern-kill-legacy-like-a-boss-db3db41564ed][The Strangler Pattern: Kill Legacy Like a Boss]]

* PROPOSED "Unignore" unknown words
- Deciders :: CE, MK
- Date :: [2024-02-21 Mi]

Unknown words can be "ignored", i.e. marked as ignored and they will
be put at the end of the list. In the paginated view of the unknown
words an ignored word will simply show up on the last page once the
transcriber has worked though all the non-ignored words.

** Context and Problem Statement

When an unknown word is confirmed an entry for this word is created in
the table for local words. The entry in the table for unknown words is
not changed. However the query for unknown words will no longer
contain that word in the resultset, as it only returns unknown words
that are not in the local words table.

So when a local word is deleted the query for unknown words will
return that word again in its resultset. So far all is fine.

However, as the row for that word in the table for unknown words has
not been touched, the unknown word will still be marked as ignored.
Does that make sense? And in a broader sense: do we need a way to
"unignore" an unknown word?

Another UI problem is that when a word is ignored it is updated in the
db and dropped from the current pagination window. There is no
re-fetch of the current pagination window. This can cause problems
when the ignored word should show up in the same window again (maybe
there is only one window left). But does a user really ignore a word
when they are in the last window?

** Decision Drivers

- Make the UI as simple as possible
- Make the UI as understandable as possible
- Make the REST API as constrained as possible
  - i.e. do not make the PUT end point of local words also reset the
    ignored status of the same unknown word
- Do not waste big engineering effort on small fish

** Considered Options

- Ignore the problem :: the use case is so rare that the users will
  almost never run into this situation
- Disable ignore button for ignored words :: Basically the same as
  ignoring the problem but make it visible that a word is ignored by
  disabling the button. "Ignoring" an already ignored unknown word
  indeed does not make much sense.
- Separate tab :: Keep the ignored words in a separate tab. Since
  switching to a tab causes a re-fetch, the problem of pagination with
  re-fetch just goes away
- Add an "Unignore" button :: Make the "Ignore" button a toggle that
  lets you ignore and "unignore" a word
- Clear the ignored state on confirm :: When confirming an unknown
  word set the ignored flag to false

** Decision Outcome

Chosen option: "Disable ignore button for ignored words", because the
problem is so rare that it does not warrant a complication of the
day-to-day user interface. The chosen option is to basically ignore
the problem but make it slightly more visible to the user that a word
is ignored.

*** Positive Consequences

- The UI stays simple

*** Negative Consequences

- There are slight inconsistencies around ignored words when you are
  on the last page or when you delete a formerly ignored word from the
  list of local words.

** Pros and Cons of the Options

*** Ignore the problem

- Good :: already done :-)
- Bad :: doesn't really solve the issue

*** Disable ignore button for ignored words

Basically the same as [[*Ignore the problem][Ignore the problem]] but at least the button to
ignore is disabled for ignored words.

- Good :: The UI is more consistent
- Bad :: doesn't really solve the issue

*** Separate tab

Add a separate tab for ignored words. Because switching to the tab
causes a refresh, we will not have the weird problems with pagination.
However the UI is getting cluttered up with another rarely used tab.

- Good :: The pagination of ignored words is more consistent
- Bad :: Clutter in the UI to solve a minuscule problem
- Bad :: A solution in search of a problem

*** Add an "Unignore" button

The "Ignore" button is more like a toggle that lets the user toggle
the isIgnored state. But then you get some weird UI issues where an
unignored entry disappears (as it is sorted back where it originally
was) where it should be back (as we are on the page it was
originally).

- Good :: seems simple and orthogonal
- Bad :: Weird UI issues with unignored words and pagination
  - These are really confusing for the user
  - and hard to fix properly

*** Clear the ignored state on confirm

When the word is confirmed, i.e. inserted into the local words table,
the isIgnored flag in the unknown words table is cleared. The happy
path seems quite sane, but what happens in the case of failure?

- Good :: A clear and easy to understand solution for the user
- Bad :: Where do you put the responsibility for this? In the UI? In
  the REST API?
- Bad :: Hard to implement the failure cases right


** Links

* ACCEPTED Show totals in paginated views
CLOSED: [2024-02-20 Di 11:26]
- Deciders :: CE
- Date :: [2024-02-15 Do]

** Context and Problem Statement

The query to get the unknown words is very complex and costly. It
currently only returns a subset of the unknown words as they are
paginated in the UI anyway. Now we would also like to see the total of
the unknown words. How do we display the total without having to do
the expensive query twice?

** Decision Drivers

- The request to get the unknown words needs to be fast

** Considered Options

- Two selects :: Using two selects, first using LIMIT and then a
  second one to get the total
- Independent selects :: There are two selects as above and the client
  asks for the information separately. I.e. the client determines when
  it asks for the information and how much of it is cached and locally
  maintained.
- ~SQL_CALC_FOUND_ROWS~ :: Using ~SQL_CALC_FOUND_ROWS~ as outlined in
  [[https://stackoverflow.com/q/818567][MySQL pagination without double-querying?]]

** Decision Outcome

Chosen option: "Independent selects", firstly because MySQL seems to
shy away from the ~SQL_CALC_FOUND_ROWS~ solution. It is deprecated as
of 8.0.17, see https://stackoverflow.com/a/62328373. Secondly leaving
it up to the client when to fetch the totals information gives us more
room for optimization, such as caching and/or just approximated
totals.

*** Positive Consequences

*** Negative Consequences

- Most of the code for the second query (to get the total) is
  duplicated from the first query. It is not quite the same though as
  it can be kept simpler.

** Pros and Cons of the Options

*** Two selects

There are two selects, but they could possibly be combined in one REST
end point. This ties the two together at least from the POV of the
client. This can make sense some time but probably most of the time
the two concerns are separate.

- Bad :: complects two mostly independent concerns

*** Independent selects

There are two concerns:

1. get a possibly paginated set of words
2. get the total number of words

These two concerns can be nicely served be two requests. The first one
is plain old REST call (~GET /api/collection~) to get the list of
words. The second one is a bit special and the idea comes from this [[https://stackoverflow.com/q/1610862][SO
question]] about "Getting a count of returns seen by a RESTful
request". The basic idea is that you send a ~HEAD~ request to the
collection and the response contains the count as meta data in the
headers.

- Good :: separates fetching the words from fetching the count
- Good :: the count just returns meta data without a body

*** ~SQL_CALC_FOUND_ROWS~

Even MySQL is dropping it, so that one is out

- Bad :: deprecated, see https://stackoverflow.com/a/62328373

** Links

- https://stackoverflow.com/q/1610862

* ACCEPTED Cleanup of dictionary_unknownword table
CLOSED: [2024-02-16 Fr 09:24]
- Deciders :: CE
- Date :: [2024-02-15 Do]

To calculate the unknown words there is some sort of a "temporary"
table that holds the extracted words from a document. This table
should probably be cleaned up once the document has been finished.

** Context and Problem Statement

The calculation of the unknown words is expensive. Previously they
were calculated when the request came in. Now the extraction of
unknown words from the XML is done when the XML is uploaded. But these
words aren't removed from the table ever. Should they be removed?

** Decision Drivers

- many rows in the table make the very complex SQL query to find
  unknown words slower
- removing them when the status changes couples the two actions too
  much, i.e. the state change and the cleanup
- Potentially there could be many cleanup jobs
  - cleanup unknown words
  - remove images
  - remove old versions
- the user is not interested in the cleanup, i.e. this is just an
  implementation detail

** Considered Options

- Do not remove :: 
- Asynchronously :: remove them with a cron job, kinda like garbage
  collection
- Synchronously :: remove them when the status of the document is set
  to finished

** Decision Outcome

Chosen option: "Asynchronously", because this keeps the two issues
separate. The state is changed immediately but the garbage is cleaned
up later/asynchronously.

*** Positive Consequences

- The response to state change is fast, as the clean is done later

*** Negative Consequences

- No user feedback that the cleanup is done

** Pros and Cons of the Options

*** Do not remove

- Good :: easy to implement
- Good :: predictable
- Bad :: waste of disc space
- Bad :: unknown words query will get slower

*** Asynchronously

The status is changed by the user but the cleanup is done
independently sometime later.

- Good :: relatively simple to implement as they are independent parts
  with no UI
- Bad :: errors are only visible to the administrators
  - but the users are not interested in these kinds of errors

*** Synchronously

The status is changed by the user and the cleanup is part of it.

- Good :: predictable
- Good :: feedback to the user if anything fails
- Bad :: state change request takes a long time
- Bad :: quite a bit of effort to implement

** Links

- [[https://github.com/sbsdev/daisyproducer2/blob/8fb6d4e4dd26e326be8050c6db2b98b9c4452fdd/src/clj/daisyproducer2/whitelists/async.clj#L60][See how cron jobs are handled for global white lists]]
- https://github.com/sbsdev/daisyproducer2/commit/94974e90a2ec28e8d6786fc28b11ecaa254c925b

* ACCEPTED Pagination for versions and images
CLOSED: [2024-02-15 Do 16:37]
- Deciders :: CE
- Date :: [2024-02-14 Mi]

The unknown words do have pagination. To be orthogonal it seems
logical that the list of versions and images also have pagination

** Context and Problem Statement

Pagination makes the version and image pages much more complicated
especially in the light of deletion of single elements. With
pagination we will have to do a re-fetch each time you delete an
element, so we can have a full window of elements again.

** Decision Drivers

- the old UI did *not* have pagination
- at least for versions we rarely have more than a handful of versions
  - so pagination seems pointless
- there is search on the page
- I don't think the users want to paginate through images let alone
  versions
- the code is much more complicated

** Considered Options

- Dropping pagination :: for images and versions
- Implementing pagination :: for images and versions

** Decision Outcome

Chosen option: "Dropping pagination", because the cost of maintaining
it is too high compared with the user benefit.

*** Positive Consequences

- Code is much simpler
- no weird re-draw effects when re-fetching the items

*** Negative Consequences

- The user cannot paginate.

** Links

- https://github.com/sbsdev/daisyproducer2/commit/fdb4de711de77f710fe6bd970c19c903772b41ca
- https://github.com/sbsdev/daisyproducer2/commit/62609888ae0442daa7de40bf0cb79665f689543b

* COMMENT [short title of solved problem and solution]                     :Template:
# - Status :: [proposed | rejected | accepted | deprecated | ... |
#   superseded by [[file:0005-example.md][ADR-0005]]]
- Deciders :: [list everyone involved in the decision]
- Date :: [YYYY-MM-DD when the decision was last updated]

Technical Story: [description | ticket/issue URL]

** Context and Problem Statement

[Describe the context and problem statement, e.g., in free form using
two to three sentences. You may want to articulate the problem in form
of a question.]

** Decision Drivers

- [driver 1, e.g., a force, facing concern, ...]
- [driver 2, e.g., a force, facing concern, ...]
- ...

** Considered Options

- [option 1]
- [option 2]
- [option 3]
- ...

** Decision Outcome

Chosen option: "[option 1]", because [justification. e.g., only option,
which meets k.o. criterion decision driver | which resolves force force
| ... | comes out best (see below)].

*** Positive Consequences

- [e.g., improvement of quality attribute satisfaction, follow-up
  decisions required, ...]
- ...

*** Negative Consequences

- [e.g., compromising quality attribute, follow-up decisions required,
  ...]
- ...

** Pros and Cons of the Options

*** [option 1]

[example | description | pointer to more information | ...]

- Good, because [argument a]
- Good, because [argument b]
- Bad, because [argument c]
- ...

*** [option 2]

[example | description | pointer to more information | ...]

- Good, because [argument a]
- Good, because [argument b]
- Bad, because [argument c]
- ...

*** [option 3]

[example | description | pointer to more information | ...]

- Good, because [argument a]
- Good, because [argument b]
- Bad, because [argument c]
- ...

** Links

- [Link type] [Link to ADR]
- ...
